"""Migration

Revision ID: 73a8d5ce1ef2
Revises: 40e8643a08f8
Create Date: 2025-11-18 07:49:12.377633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73a8d5ce1ef2'
down_revision: Union[str, Sequence[str], None] = '40e8643a08f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_path', sa.String(length=200), nullable=False))
        batch_op.drop_column('media_type')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('media_path')

    # ### end Alembic commands ###
